#!/usr/bin/perl

use warnings ;
use strict ;

my @tags = () ;

open my $fh, "grep ::usage *.m | sed 's/::usage.*//'|" or die ;
while (<$fh>)
{
   chomp ;
   /(.*):(.*)/ or die ;

   my ($filename, $symbolname) = ($1, $2) ;

   push( @tags, "$symbolname\t$filename\t/${symbolname}::usage/\n" ) ;
}
close $fh or die ;

print $_ foreach (sort @tags) ;
